Revert "toolchain: Use read-only token to check out repository (#1243)"
This reverts commit 311d820f0377ccef29626a810ce89d89a8f78d77

The action failed using this token, so trying to rely on the previous one,
error for context:

error: failed to push branch gh-pages to origin: "remote: error: GH006: Protected branch update failed for refs/heads/gh-pages.
remote: error: You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.
To https://github.com/codacy/docs
 ! [remote rejected]     gh-pages -> gh-pages (protected branch hook declined)
error: failed to push some refs to 'https://github.com/codacy/docs'"